[project]
name = "highlighting-color-pillow"
version = "0.1.0"
description = "Extension for the Pillow library"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio>=5.39.0",
    "pillow==11.3.0",
]
